---
title: "raw_analysis"
output:
  pdf_document: default
  html_document: default
editor_options:
  chunk_output_type: console
---
```{r density-theatre}
grosses %>%
  ggplot(aes(x=seats_in_theatre))+
  geom_density()
```

```{r mutate-size}
grosses_size <- grosses %>%
  mutate(theatre_size=(case_when(
    seats_in_theatre<750 ~"small",
    seats_in_theatre<1300 & seats_in_theatre>750 ~"medium",
    seats_in_theatre>1299 ~"large")
  )
  )
```

#Jeni No. 1

```{r weekly-gross-frequency}
grosses_size %>% 
  filter(theatre_size != is.na(theatre_size)) %>%
  ggplot(aes(x = weekly_gross, fill = theatre_size)) + 
  geom_histogram() +
  labs(
    title = "Frequency of Theatres by Weekly Gross Revenue",
    x = "Weekly Gross Revenue ($)", 
    y = "Frequency",
    fill = "Size of Theatre"
  ) +
  scale_x_continuous(labels = label_dollar(suffix = "M", scale = 1e-6)) 
  
```

```{r avgprice-weeklygross}
grosses %>%
  ggplot(aes(y = weekly_gross,x = avg_ticket_price)) +
  geom_point() +
  geom_smooth(se = FALSE) +
  labs(title = "Relationship Between Average Ticket Price and Gross Weekly Revenue",
       x = "Average Ticket Price",
       y = "Gross Weekly Revenue") +
  scale_y_continuous(labels = label_dollar(suffix = "M", scale = 1e-6))

grosses %>%
  ggplot(aes(y = weekly_gross,x = avg_ticket_price)) +
  geom_smooth(se = FALSE) +
  labs(title = "Relationship Between Average Ticket Price and Gross Weekly Revenue",
       x = "Average Ticket Price",
       y = "Gross Weekly Revenue") +
  scale_y_continuous(labels = label_dollar(suffix = "M", scale = 1e-6))
```

```{r model-avgprice-weeklygross}
grosses_log <- grosses%>%
  mutate(
    price_log = log(avg_ticket_price + 0.00001),
    gross_log = log(weekly_gross + 0.00001)
  )

grosses_log %>%
  ggplot(aes(x = price_log, y = gross_log)) +
  geom_point()

linear_reg() %>%
  set_engine("lm") %>%
  fit(gross_log ~ price_log, 
      data = grosses_log) %>%
  tidy()
```

```{r pctcapacity-weeklygross}
counting %>% 
  ggplot(aes(x = pct_capacity, y = weekly_gross, color = theatre_size)) + 
  geom_point(alpha = 0.5) +
  labs(title = "Percentage of Seats Capacity Sold and Weekly Gross Revenue", 
       y = "Weekly Gross Revenue", 
       x = "Percentage of Seats Capacity Sold",
       color = "Theatre Size") +
  scale_y_continuous(labels = label_dollar(suffix = "M", scale = 1e-6))
```

```{r performances-weeklygross}
grosses %>%
  ggplot(aes(x = performances, y = weekly_gross))+
  geom_jitter()
```

________________________________________________________________________

#Felix No. 2
```{r mutate week}
counting<-grosses_size%>%
  mutate(theatre_show=paste0(theatre,show))%>%
  group_by(theatre_show)%>%
  mutate(week_running=n())
```

```{r week running}
week_running_improved <- counting%>%
  summarise(avg_ticket_price,theatre_show,week_running)

improved<-aggregate(data=week_running_improved,
            week_running_improved$avg_ticket_price,
            by=list(theatre_show=week_running_improved$theatre_show,
                    week_running=week_running_improved$week_running), 
            FUN=mean)
```

```{r week-running-avg-ticket-price}
improved%>%
  ggplot(aes(x=week_running,y=x))+
  geom_smooth(se = FALSE)+
  labs(title = "Relaionship Between Week Running and Average Ticket Price",
       x = "Week Running",
       y = "Average Ticket Price")
```

```{r remove-avg-ticket-price}
grosses1<-grosses%>%
  filter(!avg_ticket_price==0)

improved%>%
  ggplot(aes(x=week_running))+
  geom_density()+
  geom_vline(xintercept=375)


improved_2<-improved%>%
  filter(week_running<375)

improved_2%>%
  ggplot(aes(x=week_running,y=x))+
  geom_smooth(se = FALSE)+
  labs(title = "Relaionship Between Week Running and Average Ticket Price",
       x = "Week Running",
       y = "Average Ticket Price")

linear_reg_week_running<-
  linear_reg()%>%
  set_engine("lm")%>%
  fit(week_running ~ x,data=improved_2)

tidy(linear_reg_week_running)
```

```{r theatre-size-avg-ticket-price}
counting%>%
  ggplot(aes(x=seats_in_theatre,y=avg_ticket_price,color=theatre_size))+
  geom_smooth(se = FALSE)+
  labs(title = "Relationship Between Theatre Size and Average Ticket Price",
       x = "Seat Capacity",
       y = "Average Ticket Price")
```



```{r model}
grosses1$avg_ticket_price2<-grosses1$avg_ticket_price^2

grosses1%>%
  ggplot(aes(x=avg_ticket_price,y=weekly_gross))+
  geom_smooth()+
  geom_point()

quadratic_model<-
  lm(grosses1$weekly_gross ~ grosses1$avg_ticket_price + 
       grosses1$avg_ticket_price2,
     data=grosses1)
summary(quadratic_model)


grosses1$avg_ticket_price1=1/grosses1$avg_ticket_price
  
  improved_model<-
    lm(grosses1$weekly_gross ~ grosses1$avg_ticket_price + 
       grosses1$avg_ticket_price2 +
       grosses1$avg_ticket_price1,
     data=grosses1)
summary(improved_model)  
```

```{r predict}
grosses_log <- grosses%>%
  summarise(
    price_log = log(avg_ticket_price + 0.00001),
    gross_log = log(weekly_gross + 0.00001)
  )

grosses_log%>%
  ggplot(aes(x=price_log, y=gross_log))+
  geom_point()+
  geom_smooth()+
  labs(title = "Log(Weekly Gross) VS. Log(Average Ticket Price)",
       x = "Log(Average Ticket Price)",
       y = "Log(Weekly Gross)")

logxy_preliminary <-
  linear_reg()%>%
  set_engine("lm")

logxy <- logxy_preliminary %>%
  fit(gross_log ~ price_log, data=grosses_log)

glance(logxy)$r.squared

set.seed(11)
grosses_split<-initial_split(grosses_log,prop = 0.8)

train_data <- training(grosses_split)
test_data <- testing(grosses_split)
glimpse(train_data)
glimpse(test_data)

grosses_rec <- recipe(gross_log ~.,data = grosses_log)%>%
  step_zv(all_predictors())

grosses_workflow <- workflow()%>%
  add_model(logxy_preliminary)%>%
  add_recipe(grosses_rec)

gross_fit<-grosses_workflow%>%
  fit(data = train_data)

gross_pred<-predict(object = gross_fit, new_data = train_data)%>%
  bind_cols(train_data%>%select(gross_log,price_log))

rsq(gross_pred, truth = gross_log, estimate = .pred)
rmse(gross_pred, truth = gross_log, estimate = .pred)

gross_pred%>%
  summarise(min = min(gross_log), max = max(gross_log))

test_pred<- predict(gross_fit, test_data)%>%
  bind_cols(test_data%>%select(gross_log,price_log))

rsq(test_pred, truth = gross_log, estimate = .pred)
rmse(test_pred, truth = gross_log, estimate = .pred)
```
